language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt

script:
  - python -m unittest
  - python -m pylint libpyvivotek
