name: pytest

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
        python-version:
          - "3.5"
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install pytest
        pip install -r requirements.txt
        pip install -r requirements_test.txt
    - name: Run tests
      run: pytest
