name: Verify

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check_types:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3'
        cache: 'pip'
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt -r requirements_test.txt
    - name: Run mypy
      run: mypy --install-types --non-interactive libpyvivotek
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3'
        cache: 'pip'
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt -r requirements_test.txt
    - name: Run pylint
      run: pylint libpyvivotek
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3'
        cache: 'pip'
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt -r requirements_test.txt
    - name: Run tests
      run: pytest
